/**
 * Generates Texas county border paths for MapUS.tsx
 * Run: npx tsx scripts/generate-texas-counties.ts
 */
import * as fs from "fs";
import * as path from "path";
import { geoPath, geoIdentity } from "d3-geo";
import * as topojson from "topojson-client";

// us-atlas albers bbox ≈ [-57.66, 12.97, 957.52, 606.57]
// MapUS viewBox: 959 593
const BBOX = [
  [-57.66, 12.97],
  [957.52, 606.57],
] as [[number, number], [number, number]];
const bboxPoly = {
  type: "Polygon" as const,
  coordinates: [
    [
      [BBOX[0][0], BBOX[0][1]],
      [BBOX[1][0], BBOX[0][1]],
      [BBOX[1][0], BBOX[1][1]],
      [BBOX[0][0], BBOX[1][1]],
      [BBOX[0][0], BBOX[0][1]],
    ],
  ],
};
const fit = geoIdentity().fitExtent(
  [
    [0, 0],
    [959, 593],
  ],
  bboxPoly
);
const pathGenerator = geoPath().projection(fit);

async function main() {
  const url =
    "https://cdn.jsdelivr.net/npm/us-atlas@3/counties-albers-10m.json";
  const res = await fetch(url);
  const topology = (await res.json()) as topojson.Topology;

  const counties = topology.objects.counties as topojson.GeometryCollection;
  if (!counties) throw new Error("No counties in topology");

  // Texas state FIPS = 48. Filter Texas counties (id starts with 48)
  const texasCounties = counties.geometries.filter(
    (g) => typeof g.id === "string" && g.id.startsWith("48")
  );

  if (texasCounties.length === 0) {
    throw new Error("No Texas counties found");
  }

  // Create mesh of Texas county boundaries (internal borders only)
  const mesh = topojson.mesh(topology, counties, (a, b) => {
    const aId = String((a as { id?: string }).id ?? "");
    const bId = String((b as { id?: string }).id ?? "");
    const aIsTx = aId.startsWith("48");
    const bIsTx = bId.startsWith("48");
    return aIsTx && bIsTx;
  });

  const meshPath = pathGenerator(mesh);
  if (!meshPath) throw new Error("Failed to generate mesh path");

  const outPath = path.join(process.cwd(), "src/components/maps/texas-counties-path.ts");
  fs.writeFileSync(
    outPath,
    `// Auto-generated by scripts/generate-texas-counties.ts - Texas county borders for MapUS
export const TEXAS_COUNTIES_PATH = "${meshPath}";
`
  );
  console.log("Wrote", outPath);
}

main().catch(console.error);
